# Generated by Django 3.0.7 on 2020-06-16 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PakistanPopulationByYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(db_column='year', default='', max_length=255)),
                ('totalPopulation', models.CharField(db_column='totalPopulation', default='', max_length=255)),
                ('growthRate', models.CharField(db_column='growthRate', default='', max_length=255)),
                ('density', models.CharField(db_column='density', default='', max_length=255)),
                ('totalPopulationRank', models.CharField(db_column='totalPopulationRank', default='', max_length=255)),
                ('densityRank', models.CharField(db_column='densityRank', default='', max_length=255)),
            ],
            options={
                'db_table': 'pakistan_population_by_year',
            },
        ),
        migrations.CreateModel(
            name='WorldPopulationByCountryName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', default='', max_length=255)),
                ('population', models.CharField(db_column='population', default='', max_length=255)),
                ('area', models.CharField(db_column='area', default='', max_length=255)),
                ('Density', models.CharField(db_column='Density', default='', max_length=255)),
                ('WorldPercentage', models.CharField(db_column='WorldPercentage', default='', max_length=255)),
                ('rank', models.CharField(db_column='rank', default='', max_length=255)),
            ],
            options={
                'db_table': 'world_pop_by_country_name',
            },
        ),
        migrations.CreateModel(
            name='WorldPopulationGrowthRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(db_column='year', default='', max_length=255)),
                ('value', models.CharField(db_column='value', default='', max_length=255)),
                ('growthRate', models.CharField(db_column='GrowthRate', default='', max_length=255)),
            ],
            options={
                'db_table': 'world_pop_growth_rate',
            },
        ),
        migrations.CreateModel(
            name='WorldPopulationProjectedGrowthRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(db_column='year', default='', max_length=255)),
                ('value', models.CharField(db_column='value', default='', max_length=255)),
                ('growthRate', models.CharField(db_column='GrowthRate', default='', max_length=255)),
            ],
            options={
                'db_table': 'world_pop_projected_growth_rate',
            },
        ),
    ]
