# Generated by Django 3.0.7 on 2020-06-16 07:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('import_Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PakistanProjectedPopulationByYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.CharField(db_column='year', default='', max_length=255)),
                ('totalPopulation', models.CharField(db_column='totalPopulation', default='', max_length=255)),
                ('growthRate', models.CharField(db_column='growthRate', default='', max_length=255)),
                ('density', models.CharField(db_column='density', default='', max_length=255)),
                ('PopulationRank', models.CharField(db_column='populationRank', default='', max_length=255)),
                ('densityRank', models.CharField(db_column='densityRank', default='', max_length=255)),
            ],
            options={
                'db_table': 'pakistan_projected_pop_by_year',
            },
        ),
    ]
