# Generated by Django 3.0.7 on 2020-06-24 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('import_Data', '0002_pakistanprojectedpopulationbyyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='PakistanDetailCensusData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(db_column='city', default='', max_length=255)),
                ('province', models.CharField(db_column='province', default='', max_length=255)),
                ('area', models.FloatField(db_column='area', default=0)),
                ('population_1998', models.FloatField(db_column='population_1998', default=0)),
                ('male_pop', models.FloatField(db_column='male_pop', default=0)),
                ('female_pop', models.FloatField(db_column='female_pop', default=0)),
                ('sex_ratio', models.FloatField(db_column='sex_ratio', default=0)),
                ('population_density', models.FloatField(db_column='population_density', default=0)),
                ('urban_population', models.FloatField(db_column='urban_population', default=0)),
                ('rural_population', models.FloatField(db_column='rural_population', default=0)),
                ('average_household_size', models.FloatField(db_column='average_household_size', default=0)),
                ('literacy_ratio', models.FloatField(db_column='literacy_ratio', default=0)),
                ('male_literacy_ratio', models.FloatField(db_column='male_literacy_ratio', default=0)),
                ('female_literacy_ratio', models.FloatField(db_column='female_literacy_ratio', default=0)),
                ('population_1981', models.FloatField(db_column='population_1981', default=0)),
                ('annual_growth_rate', models.FloatField(db_column='annual_growth_rate', default=0)),
                ('total_housing_unit', models.FloatField(db_column='total_housing_unit', default=0)),
                ('pacca_housing_unit', models.FloatField(db_column='pacca_housing_unit', default=0)),
                ('electricity_housing_unit', models.FloatField(db_column='electricity_housing_unit', default=0)),
                ('water_housing_unit', models.FloatField(db_column='water_housing_unit', default=0)),
                ('gas_housing_unit', models.FloatField(db_column='gas_housing_unit', default=0)),
                ('tehsils', models.FloatField(db_column='tehsils', default=0)),
                ('union_councils', models.FloatField(db_column='union_councils', default=0)),
                ('mauzas', models.FloatField(db_column='mauzas', default=0)),
                ('municipal_committees', models.FloatField(db_column='municipal_committees', default=0)),
                ('town_committees', models.FloatField(db_column='town_committees', default=0)),
            ],
            options={
                'db_table': 'pakistan_detail_census_data',
            },
        ),
    ]
