# Generated by Django 3.0.7 on 2020-06-25 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('import_Data', '0003_pakistandetailcensusdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PakistanCensusPercentageData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(db_column='city', default='', max_length=255)),
                ('province', models.CharField(db_column='province', default='', max_length=255)),
                ('male_pop', models.FloatField(db_column='male_pop', default=0)),
                ('female_pop', models.FloatField(db_column='female_pop', default=0)),
                ('urban_pop', models.FloatField(db_column='urban_pop', default=0)),
                ('rural_pop', models.FloatField(db_column='rural_pop', default=0)),
                ('pacca_housing_unit', models.FloatField(db_column='pacca_housing_unit', default=0)),
                ('electricity_housing_unit', models.FloatField(db_column='electricity_housing_unit', default=0)),
                ('water_housing_unit', models.FloatField(db_column='water_housing_unit', default=0)),
                ('gas_housing_unit', models.FloatField(db_column='gas_housing_unit', default=0)),
            ],
            options={
                'db_table': 'pakistan_census_percentage_data',
            },
        ),
    ]
