# Generated by Django 3.0.7 on 2020-06-25 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('import_Data', '0004_pakistancensuspercentagedata'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='pakistandetailcensusdata',
            name='percentage_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='import_Data.PakistanCensusPercentageData'),
        ),
    ]
